export const threeColumnJson = {
  tagName: 'mjml',
  children: [
    {
      tagName: 'mj-head',
      attributes: {},
      children: [
        { tagName: 'mj-title', content: 'ZG5kZS1lZGl0b3I=' },
        { tagName: 'mj-style', content: 'YXt0ZXh0LWRlY29yYXRpb246bm9uZSFpbXBvcnRhbnR9CgouYm9keSB7fSA=' },
        {
          tagName: 'mj-attributes',
          children: [
            {
              tagName: 'mj-text',
              attributes: {
                'font-family':
                  'Ubuntu,Andada Pro,Festive,Fira Sans,Georama,IM Fell English SC,Inter,Lato,Lora,Merriweather,Montserrat,Noto Sans Mono,Noto sans,Nunito,Nunito Sans,Open Sans,Open Sans Condensed,Oswald,PT Sans,Playfair Display,Poppins,Quicksand,Raleway,Roboto,Roboto Condensed,Roboto Mono,Roboto Slab,Rubix,Scheherazade New,Source Sans Pro,Ubuntu,Work Sans',
              },
            },
          ],
        },
        {
          tagName: 'mj-font',
          attributes: { name: 'Roboto', href: 'https://fonts.googleapis.com/css2?family=Roboto&display=swap' },
        },
        {
          tagName: 'mj-font',
          attributes: { name: 'Festive', href: 'https://fonts.googleapis.com/css2?family=Festive&display=swap' },
        },
        {
          tagName: 'mj-font',
          attributes: {
            name: 'Noto Sans Mono',
            href: 'https://fonts.googleapis.com/css2?family=Noto+Sans+Mono&display=swap',
          },
        },
        {
          tagName: 'mj-font',
          attributes: {
            name: 'Open Sans',
            href: 'https://fonts.googleapis.com/css2?family=Open+Sans&display=swap',
          },
        },
        {
          tagName: 'mj-font',
          attributes: {
            name: 'Andada Pro',
            href: 'https://fonts.googleapis.com/css2?family=Andada+Pro&display=swap',
          },
        },
        {
          tagName: 'mj-font',
          attributes: { name: 'Lato', href: 'https://fonts.googleapis.com/css2?family=Lato&display=swap' },
        },
        {
          tagName: 'mj-font',
          attributes: {
            name: 'Scheherazade New',
            href: 'https://fonts.googleapis.com/css2?family=Scheherazade+New&display=swap',
          },
        },
        {
          tagName: 'mj-font',
          attributes: {
            name: 'Montserrat',
            href: 'https://fonts.googleapis.com/css2?family=Montserrat&display=swap',
          },
        },
        {
          tagName: 'mj-font',
          attributes: {
            name: 'Roboto Condensed',
            href: 'https://fonts.googleapis.com/css2?family=Roboto+Condensed&display=swap',
          },
        },
        {
          tagName: 'mj-font',
          attributes: {
            name: 'Source Sans Pro',
            href: 'https://fonts.googleapis.com/css2?family=Source+Sans+Pro&display=swap',
          },
        },
        {
          tagName: 'mj-font',
          attributes: { name: 'Poppins', href: 'https://fonts.googleapis.com/css2?family=Poppins&display=swap' },
        },
        {
          tagName: 'mj-font',
          attributes: { name: 'Oswald', href: 'https://fonts.googleapis.com/css2?family=Oswald&display=swap' },
        },
        {
          tagName: 'mj-font',
          attributes: {
            name: 'Noto sans',
            href: 'https://fonts.googleapis.com/css2?family=Noto+sans&display=swap',
          },
        },
        {
          tagName: 'mj-font',
          attributes: { name: 'Georama', href: 'https://fonts.googleapis.com/css2?family=Georama&display=swap' },
        },
        {
          tagName: 'mj-font',
          attributes: {
            name: 'Roboto Mono',
            href: 'https://fonts.googleapis.com/css2?family=Roboto+Mono&display=swap',
          },
        },
        {
          tagName: 'mj-font',
          attributes: { name: 'Raleway', href: 'https://fonts.googleapis.com/css2?family=Raleway&display=swap' },
        },
        {
          tagName: 'mj-font',
          attributes: { name: 'Nunito', href: 'https://fonts.googleapis.com/css2?family=Nunito&display=swap' },
        },
        {
          tagName: 'mj-font',
          attributes: {
            name: 'Roboto Slab',
            href: 'https://fonts.googleapis.com/css2?family=Roboto+Slab&display=swap',
          },
        },
        {
          tagName: 'mj-font',
          attributes: { name: 'PT Sans', href: 'https://fonts.googleapis.com/css2?family=PT+Sans&display=swap' },
        },
        {
          tagName: 'mj-font',
          attributes: {
            name: 'Merriweather',
            href: 'https://fonts.googleapis.com/css2?family=Merriweather&display=swap',
          },
        },
        {
          tagName: 'mj-font',
          attributes: {
            name: 'Playfair Display',
            href: 'https://fonts.googleapis.com/css2?family=Playfair+Display&display=swap',
          },
        },
        {
          tagName: 'mj-font',
          attributes: { name: 'Lora', href: 'https://fonts.googleapis.com/css2?family=Lora&display=swap' },
        },
        {
          tagName: 'mj-font',
          attributes: { name: 'Rubix', href: 'https://fonts.googleapis.com/css2?family=Rubix&display=swap' },
        },
        {
          tagName: 'mj-font',
          attributes: {
            name: 'IM Fell English SC',
            href: 'https://fonts.googleapis.com/css2?family=IM+Fell+English+SC&display=swap',
          },
        },
        {
          tagName: 'mj-font',
          attributes: {
            name: 'Open Sans Condensed',
            href: 'https://fonts.googleapis.com/css2?family=Open+Sans+Condensed&display=swap',
          },
        },
        {
          tagName: 'mj-font',
          attributes: { name: 'Inter', href: 'https://fonts.googleapis.com/css2?family=Inter&display=swap' },
        },
        {
          tagName: 'mj-font',
          attributes: {
            name: 'Nunito Sans',
            href: 'https://fonts.googleapis.com/css2?family=Nunito+Sans&display=swap',
          },
        },
        {
          tagName: 'mj-font',
          attributes: {
            name: 'Work Sans',
            href: 'https://fonts.googleapis.com/css2?family=Work+Sans&display=swap',
          },
        },
        {
          tagName: 'mj-font',
          attributes: {
            name: 'Quicksand',
            href: 'https://fonts.googleapis.com/css2?family=Quicksand&display=swap',
          },
        },
        {
          tagName: 'mj-font',
          attributes: {
            name: 'Fira Sans',
            href: 'https://fonts.googleapis.com/css2?family=Fira+Sans&display=swap',
          },
        },
        {
          tagName: 'mj-font',
          attributes: { name: 'Ubuntu', href: 'https://fonts.googleapis.com/css2?family=Ubuntu&display=swap' },
        },
      ],
    },
    {
      tagName: 'mj-body',
      attributes: { 'css-class': 'mjml-tag body identifier-mj-body', 'background-color': 'grey', width: '600px' },
      children: [
        {
          tagName: 'mj-section',
          attributes: {
            align: 'center',
            'background-color': '#ff0000ff',
            border: 'none',
            'border-radius': '0px',
            color: '#ffffff',
            'font-family': 'Ubuntu, Helvetica, Arial, sans-serif',
            'font-size': '13px',
            'font-weight': 'normal',
            'inner-padding': '10px 25px',
            'line-height': '120%',
            padding: '10px 25px',
            target: '_blank',
            'text-align': 'center',
            'text-decoration': 'none',
            'text-transform': 'none',
            'vertical-align': 'middle',
            'css-class': '   mjml-tag  identifier-mj-section-67',
            'border-left': '10px solid #e6e6e6',
            'border-right': '10px solid #e6e6e6',
            'border-top': '10px solid #e6e6e6',
            'border-bottom': '10px none #e6e6e6',
            'padding-right': '0',
            'padding-left': '0',
            'padding-top': '0',
            'padding-bottom': '0',
          },
          children: [
            {
              tagName: 'mj-column',
              attributes: { 'css-class': '   mjml-tag  identifier-mj-column-66', padding: '0px 0px' },
              children: [
                {
                  tagName: 'mj-image',
                  attributes: {
                    align: 'left',
                    border: 'none',
                    'border-top': '0px none #000',
                    'border-bottom': '0px none #000',
                    'border-left': '0px none #000',
                    'border-right': '0px none #000',
                    height: 'auto',
                    padding: '0px 8px',
                    target: '_blank',
                    width: '166',
                    'css-class': '    mjml-tag  identifier-mj-image-64',
                    src: 'https://www.grouprm.net/wp-content/uploads/2021/12/grouprm.png',
                    'padding-top': '16px',
                    'padding-bottom': '8px',
                    'padding-left': '8px',
                    'padding-right': '0px',
                  },
                  children: [],
                  mutableProperties: [
                    'align',
                    'alt',
                    'border',
                    'border-top',
                    'border-bottom',
                    'border-left',
                    'border-right',
                    'border-radius',
                    'container-background-color',
                    'css-class',
                    'fluid-on-mobile',
                    'height',
                    'href',
                    'name',
                    'padding',
                    'padding-bottom',
                    'padding-left',
                    'padding-right',
                    'padding-top',
                    'rel',
                    'sizes',
                    'src',
                    'srcset',
                    'target',
                    'title',
                    'usemap',
                    'width',
                  ],
                  mutalbePropertiesWithDefaultValues: {
                    align: 'center',
                    alt: '',
                    border: 'none',
                    'border-top': 'none',
                    'border-bottom': 'none',
                    'border-left': 'none',
                    'border-right': 'none',
                    'border-radius': '',
                    'container-background-color': '',
                    'css-class': '',
                    'fluid-on-mobile': '',
                    height: 'auto',
                    href: '',
                    name: '',
                    padding: '10px 25px',
                    'padding-bottom': '',
                    'padding-left': '',
                    'padding-right': '',
                    'padding-top': '',
                    rel: '',
                    sizes: '',
                    src: '',
                    srcset: '',
                    target: '_blank',
                    title: '',
                    usemap: '',
                    width: '100%',
                  },
                },
                {
                  tagName: 'mj-text',
                  attributes: {
                    color: '#000000',
                    'font-size': '13px',
                    'line-height': '1.6',
                    'letter-spacing': 'none',
                    align: 'center',
                    padding: '10px 25px',
                    'padding-left': '8px',
                    'padding-right': '8px',
                    'css-class': '   mjml-tag  identifier-mj-text-65',
                    'padding-top': '16px',
                    'padding-bottom': '40px',
                  },
                  content:
                    'PGZvbnQgc2l6ZT0iNiIgY29sb3I9IiNmZmZmZmYiPkFQUFJPVkVEIEdST1VQIFJFUVVFU1QgJHt7cmVxdWVzdF9pZH19PC9mb250Pg==',
                  mutableProperties: [
                    'color',
                    'font-family',
                    'font-size',
                    'font-style',
                    'font-weight',
                    'line-height',
                    'letter-spacing',
                    'height',
                    'text-decoration',
                    'text-transform',
                    'align',
                    'container-background-color',
                    'padding',
                    'padding-top',
                    'padding-bottom',
                    'padding-left',
                    'padding-right',
                    'css-class',
                  ],
                  mutalbePropertiesWithDefaultValues: {
                    color: '#000000',
                    'font-family': 'Ubuntu, Helvetica, Arial, sans-serif',
                    'font-size': '13px',
                    'font-style': '',
                    'font-weight': '',
                    'line-height': '1',
                    'letter-spacing': 'none',
                    height: '',
                    'text-decoration': '',
                    'text-transform': '',
                    align: 'left',
                    'container-background-color': '',
                    padding: '10px 25px',
                    'padding-top': '',
                    'padding-bottom': '',
                    'padding-left': '',
                    'padding-right': '',
                    'css-class': '',
                  },
                },
              ],
              mutableProperties: [
                'background-color',
                'inner-background-color',
                'border',
                'border-bottom',
                'border-left',
                'border-right',
                'border-top',
                'border-radius',
                'inner-border',
                'inner-border-bottom',
                'inner-border-left',
                'inner-border-right',
                'inner-border-top',
                'inner-border-radius',
                'width',
                'vertical-align',
                'padding',
                'padding-top',
                'padding-bottom',
                'padding-left',
                'padding-right',
                'css-class',
              ],
            },
          ],
          cannot_have: ['mj-section', 'mj-column'],
          mutableProperties: [
            'background-color',
            'background-position',
            'background-position-x',
            'background-position-y',
            'background-repeat',
            'background-size',
            'background-url',
            'border',
            'border-bottom',
            'border-left',
            'border-radius',
            'border-right',
            'border-top',
            'css-class',
            'direction',
            'full-width',
            'padding',
            'padding-bottom',
            'padding-left',
            'padding-right',
            'padding-top',
            'text-align',
          ],
        },
        {
          tagName: 'mj-section',
          attributes: {
            align: 'center',
            'background-color': '#ffffffff',
            border: 'none',
            'border-radius': '0px',
            color: '#ffffff',
            'font-family': 'Ubuntu, Helvetica, Arial, sans-serif',
            'font-size': '13px',
            'font-weight': 'normal',
            'inner-padding': '10px 25px',
            'line-height': '120%',
            padding: '10px 25px',
            target: '_blank',
            'text-align': 'center',
            'text-decoration': 'none',
            'text-transform': 'none',
            'vertical-align': 'middle',
            'css-class': '   mjml-tag  identifier-mj-section-30',
            'border-left': '10px solid #e6e6e6',
            'border-right': '10px solid #e6e6e6',
            'border-top': '0px none #e6e6e6',
            'border-bottom': '10px none #e6e6e6',
            'padding-right': '0',
            'padding-left': '0',
            'padding-top': '0',
            'padding-bottom': '10px',
          },
          children: [
            {
              tagName: 'mj-column',
              attributes: {
                'css-class': '   mjml-tag  identifier-mj-column-29',
                padding: '0px 0px',
                'padding-left': '8px',
                'padding-right': '8px',
                width: '33%',
                'vertical-align': 'middle',
              },
              children: [
                {
                  tagName: 'mj-image',
                  attributes: {
                    src: 'https://dev.bluepie.in/assets/87583817874843.svg',
                    'css-class': 'mj-placeholder',
                    width: '120px',
                  },
                },
                {
                  tagName: 'mj-text',
                  attributes: {
                    'padding-top': '0px',
                    'font-size': '16px',
                    align: 'center',
                    'css-class': 'mj-placeholder',
                  },
                  content: 'V2toS2FGcDVRbWhpYlZGbldraEtkbU5EUW1oSlIwNTJZbTVTYkdKdVVXZFpiWGgyV1RKeloyRkhWbmxhVTBVOQ==',
                },
              ],
              mutableProperties: [
                'background-color',
                'inner-background-color',
                'border',
                'border-bottom',
                'border-left',
                'border-right',
                'border-top',
                'border-radius',
                'inner-border',
                'inner-border-bottom',
                'inner-border-left',
                'inner-border-right',
                'inner-border-top',
                'inner-border-radius',
                'width',
                'vertical-align',
                'padding',
                'padding-top',
                'padding-bottom',
                'padding-left',
                'padding-right',
                'css-class',
              ],
            },
            {
              tagName: 'mj-column',
              attributes: {
                'css-class': ' mjml-tag  identifier-mj-column-75',
                padding: '0px 0px',
                width: '33%',
                'vertical-align': 'middle',
              },
              children: [
                {
                  tagName: 'mj-image',
                  attributes: {
                    src: 'https://dev.bluepie.in/assets/87583817874843.svg',
                    'css-class': 'mj-placeholder',
                    width: '120px',
                  },
                },
                {
                  tagName: 'mj-text',
                  attributes: {
                    'padding-top': '0px',
                    'font-size': '16px',
                    align: 'center',
                    'css-class': 'mj-placeholder',
                  },
                  content: 'V2toS2FGcDVRbWhpYlZGbldraEtkbU5EUW1oSlIwNTJZbTVTYkdKdVVXZFpiWGgyV1RKeloyRkhWbmxhVTBVOQ==',
                },
              ],
              mutableProperties: [
                'background-color',
                'inner-background-color',
                'border',
                'border-bottom',
                'border-left',
                'border-right',
                'border-top',
                'border-radius',
                'inner-border',
                'inner-border-bottom',
                'inner-border-left',
                'inner-border-right',
                'inner-border-top',
                'inner-border-radius',
                'width',
                'vertical-align',
                'padding',
                'padding-top',
                'padding-bottom',
                'padding-left',
                'padding-right',
                'css-class',
              ],
            },
            {
              tagName: 'mj-column',
              attributes: {
                'css-class': ' mjml-tag  identifier-mj-column-88',
                padding: '0px 0px',
                width: '33%',
                'vertical-align': 'middle',
              },
              children: [
                {
                  tagName: 'mj-image',
                  attributes: {
                    src: 'https://dev.bluepie.in/assets/87583817874843.svg',
                    'css-class': 'mj-placeholder',
                    width: '120px',
                  },
                },
                {
                  tagName: 'mj-text',
                  attributes: {
                    'padding-top': '0px',
                    'font-size': '16px',
                    align: 'center',
                    'css-class': 'mj-placeholder',
                  },
                  content: 'V2toS2FGcDVRbWhpYlZGbldraEtkbU5EUW1oSlIwNTJZbTVTYkdKdVVXZFpiWGgyV1RKeloyRkhWbmxhVTBVOQ==',
                },
              ],
              mutableProperties: [
                'background-color',
                'inner-background-color',
                'border',
                'border-bottom',
                'border-left',
                'border-right',
                'border-top',
                'border-radius',
                'inner-border',
                'inner-border-bottom',
                'inner-border-left',
                'inner-border-right',
                'inner-border-top',
                'inner-border-radius',
                'width',
                'vertical-align',
                'padding',
                'padding-top',
                'padding-bottom',
                'padding-left',
                'padding-right',
                'css-class',
              ],
            },
          ],
          cannot_have: ['mj-section', 'mj-column'],
          mutableProperties: [
            'background-color',
            'background-position',
            'background-position-x',
            'background-position-y',
            'background-repeat',
            'background-size',
            'background-url',
            'border',
            'border-bottom',
            'border-left',
            'border-radius',
            'border-right',
            'border-top',
            'css-class',
            'direction',
            'full-width',
            'padding',
            'padding-bottom',
            'padding-left',
            'padding-right',
            'padding-top',
            'text-align',
          ],
        },
        {
          tagName: 'mj-section',
          attributes: {
            align: 'center',
            'background-color': '#ffffffff',
            border: 'none',
            'border-radius': '0px',
            color: '#ffffff',
            'font-family': 'Ubuntu, Helvetica, Arial, sans-serif',
            'font-size': '13px',
            'font-weight': 'normal',
            'inner-padding': '10px 25px',
            'line-height': '120%',
            padding: '10px 25px',
            target: '_blank',
            'text-align': 'center',
            'text-decoration': 'none',
            'text-transform': 'none',
            'vertical-align': 'middle',
            'css-class': ' mjml-tag  identifier-mj-section-5',
            'border-left': '10px solid #e6e6e6',
            'border-right': '10px solid #e6e6e6',
            'border-top': '0px none #e6e6e6',
            'border-bottom': '10px none #e6e6e6',
            'padding-right': '0',
            'padding-left': '0',
            'padding-top': '0',
            'padding-bottom': '0',
          },
          children: [
            {
              tagName: 'mj-column',
              attributes: {
                'css-class': ' mjml-tag  identifier-mj-column-4',
                padding: '0px 0px',
                'padding-left': '8px',
                'padding-right': '8px',
                width: '33%',
              },
              children: [
                {
                  tagName: 'mj-image',
                  attributes: {
                    src: 'https://dev.bluepie.in/assets/87583817874843.svg',
                    'css-class': 'mj-placeholder',
                    width: '120px',
                  },
                },
                {
                  tagName: 'mj-text',
                  attributes: {
                    'padding-top': '0px',
                    'font-size': '16px',
                    align: 'center',
                    'css-class': 'mj-placeholder',
                  },
                  content: 'ZHJhZyBhbmQgZHJvcCBhIGNvbnRlbnQgYmxvY2sgaGVyZSE=',
                },
              ],
              mutableProperties: [
                'background-color',
                'inner-background-color',
                'border',
                'border-bottom',
                'border-left',
                'border-right',
                'border-top',
                'border-radius',
                'inner-border',
                'inner-border-bottom',
                'inner-border-left',
                'inner-border-right',
                'inner-border-top',
                'inner-border-radius',
                'width',
                'vertical-align',
                'padding',
                'padding-top',
                'padding-bottom',
                'padding-left',
                'padding-right',
                'css-class',
              ],
            },
            {
              tagName: 'mj-column',
              attributes: { 'css-class': ' mjml-tag  identifier-mj-column-80', padding: '0px 0px', width: '33%' },
              children: [
                {
                  tagName: 'mj-image',
                  attributes: {
                    src: 'https://dev.bluepie.in/assets/87583817874843.svg',
                    'css-class': ' mj-placeholder',
                    width: '120px',
                  },
                },
                {
                  tagName: 'mj-text',
                  attributes: {
                    'padding-top': '0px',
                    'font-size': '16px',
                    align: 'center',
                    'css-class': ' mj-placeholder',
                  },
                  content: 'ZHJhZyBhbmQgZHJvcCBhIGNvbnRlbnQgYmxvY2sgaGVyZSE=',
                },
              ],
              mutableProperties: [
                'background-color',
                'inner-background-color',
                'border',
                'border-bottom',
                'border-left',
                'border-right',
                'border-top',
                'border-radius',
                'inner-border',
                'inner-border-bottom',
                'inner-border-left',
                'inner-border-right',
                'inner-border-top',
                'inner-border-radius',
                'width',
                'vertical-align',
                'padding',
                'padding-top',
                'padding-bottom',
                'padding-left',
                'padding-right',
                'css-class',
              ],
            },
            {
              tagName: 'mj-column',
              attributes: { 'css-class': ' mjml-tag  identifier-mj-column-93', padding: '0px 0px', width: '33%' },
              children: [
                {
                  tagName: 'mj-image',
                  attributes: {
                    src: 'https://dev.bluepie.in/assets/87583817874843.svg',
                    'css-class': ' mj-placeholder',
                    width: '120px',
                  },
                },
                {
                  tagName: 'mj-text',
                  attributes: {
                    'padding-top': '0px',
                    'font-size': '16px',
                    align: 'center',
                    'css-class': ' mj-placeholder',
                  },
                  content: 'ZHJhZyBhbmQgZHJvcCBhIGNvbnRlbnQgYmxvY2sgaGVyZSE=',
                },
              ],
              mutableProperties: [
                'background-color',
                'inner-background-color',
                'border',
                'border-bottom',
                'border-left',
                'border-right',
                'border-top',
                'border-radius',
                'inner-border',
                'inner-border-bottom',
                'inner-border-left',
                'inner-border-right',
                'inner-border-top',
                'inner-border-radius',
                'width',
                'vertical-align',
                'padding',
                'padding-top',
                'padding-bottom',
                'padding-left',
                'padding-right',
                'css-class',
              ],
            },
          ],
          cannot_have: ['mj-section', 'mj-column'],
          mutableProperties: [
            'background-color',
            'background-position',
            'background-position-x',
            'background-position-y',
            'background-repeat',
            'background-size',
            'background-url',
            'border',
            'border-bottom',
            'border-left',
            'border-radius',
            'border-right',
            'border-top',
            'css-class',
            'direction',
            'full-width',
            'padding',
            'padding-bottom',
            'padding-left',
            'padding-right',
            'padding-top',
            'text-align',
          ],
        },
        {
          tagName: 'mj-section',
          attributes: {
            align: 'center',
            'background-color': '#ffffffff',
            border: 'none',
            'border-radius': '0px',
            color: '#ffffff',
            'font-family': 'Ubuntu, Helvetica, Arial, sans-serif',
            'font-size': '13px',
            'font-weight': 'normal',
            'inner-padding': '10px 25px',
            'line-height': '120%',
            padding: '10px 25px',
            target: '_blank',
            'text-align': 'center',
            'text-decoration': 'none',
            'text-transform': 'none',
            'vertical-align': 'middle',
            'css-class': '   mjml-tag  identifier-mj-section-35',
            'border-left': '10px solid #e6e6e6',
            'border-right': '10px solid #e6e6e6',
            'border-top': '0px none #e6e6e6',
            'border-bottom': '10px none #e6e6e6',
            'padding-right': '0',
            'padding-left': '0',
            'padding-top': '0',
            'padding-bottom': '0',
          },
          children: [
            {
              tagName: 'mj-column',
              attributes: {
                'css-class': '   mjml-tag  identifier-mj-column-34',
                padding: '0px 0px',
                'padding-left': '8px',
                'padding-right': '8px',
                width: '33%',
                'vertical-align': 'middle',
              },
              children: [
                {
                  tagName: 'mj-image',
                  attributes: {
                    src: 'https://dev.bluepie.in/assets/87583817874843.svg',
                    'css-class': 'mj-placeholder',
                    width: '120px',
                  },
                },
                {
                  tagName: 'mj-text',
                  attributes: {
                    'padding-top': '0px',
                    'font-size': '16px',
                    align: 'center',
                    'css-class': 'mj-placeholder',
                  },
                  content: 'ZHJhZyBhbmQgZHJvcCBhIGNvbnRlbnQgYmxvY2sgaGVyZSE=',
                },
              ],
              mutableProperties: [
                'background-color',
                'inner-background-color',
                'border',
                'border-bottom',
                'border-left',
                'border-right',
                'border-top',
                'border-radius',
                'inner-border',
                'inner-border-bottom',
                'inner-border-left',
                'inner-border-right',
                'inner-border-top',
                'inner-border-radius',
                'width',
                'vertical-align',
                'padding',
                'padding-top',
                'padding-bottom',
                'padding-left',
                'padding-right',
                'css-class',
              ],
            },
            {
              tagName: 'mj-column',
              attributes: {
                'css-class': ' mjml-tag  identifier-mj-column-83',
                padding: '0px 0px',
                width: '33%',
                'vertical-align': 'middle',
              },
              children: [
                {
                  tagName: 'mj-image',
                  attributes: {
                    src: 'https://dev.bluepie.in/assets/87583817874843.svg',
                    'css-class': 'mj-placeholder',
                    width: '120px',
                  },
                },
                {
                  tagName: 'mj-text',
                  attributes: {
                    'padding-top': '0px',
                    'font-size': '16px',
                    align: 'center',
                    'css-class': 'mj-placeholder',
                  },
                  content: 'ZHJhZyBhbmQgZHJvcCBhIGNvbnRlbnQgYmxvY2sgaGVyZSE=',
                },
              ],
              mutableProperties: [
                'background-color',
                'inner-background-color',
                'border',
                'border-bottom',
                'border-left',
                'border-right',
                'border-top',
                'border-radius',
                'inner-border',
                'inner-border-bottom',
                'inner-border-left',
                'inner-border-right',
                'inner-border-top',
                'inner-border-radius',
                'width',
                'vertical-align',
                'padding',
                'padding-top',
                'padding-bottom',
                'padding-left',
                'padding-right',
                'css-class',
              ],
            },
            {
              tagName: 'mj-column',
              attributes: { 'css-class': ' mjml-tag  identifier-mj-column-96', padding: '0px 0px', width: '33%' },
              children: [
                {
                  tagName: 'mj-image',
                  attributes: {
                    src: 'https://dev.bluepie.in/assets/87583817874843.svg',
                    'css-class': ' mj-placeholder',
                    width: '120px',
                  },
                },
                {
                  tagName: 'mj-text',
                  attributes: {
                    'padding-top': '0px',
                    'font-size': '16px',
                    align: 'center',
                    'css-class': ' mj-placeholder',
                  },
                  content: 'ZHJhZyBhbmQgZHJvcCBhIGNvbnRlbnQgYmxvY2sgaGVyZSE=',
                },
              ],
              mutableProperties: [
                'background-color',
                'inner-background-color',
                'border',
                'border-bottom',
                'border-left',
                'border-right',
                'border-top',
                'border-radius',
                'inner-border',
                'inner-border-bottom',
                'inner-border-left',
                'inner-border-right',
                'inner-border-top',
                'inner-border-radius',
                'width',
                'vertical-align',
                'padding',
                'padding-top',
                'padding-bottom',
                'padding-left',
                'padding-right',
                'css-class',
              ],
            },
          ],
          cannot_have: ['mj-section', 'mj-column'],
          mutableProperties: [
            'background-color',
            'background-position',
            'background-position-x',
            'background-position-y',
            'background-repeat',
            'background-size',
            'background-url',
            'border',
            'border-bottom',
            'border-left',
            'border-radius',
            'border-right',
            'border-top',
            'css-class',
            'direction',
            'full-width',
            'padding',
            'padding-bottom',
            'padding-left',
            'padding-right',
            'padding-top',
            'text-align',
          ],
        },
        {
          tagName: 'mj-section',
          attributes: {
            align: 'center',
            'background-color': '#ffffffff',
            border: 'none',
            'border-radius': '0px',
            color: '#ffffff',
            'font-family': 'Ubuntu, Helvetica, Arial, sans-serif',
            'font-size': '13px',
            'font-weight': 'normal',
            'inner-padding': '10px 25px',
            'line-height': '120%',
            padding: '10px 25px',
            target: '_blank',
            'text-align': 'center',
            'text-decoration': 'none',
            'text-transform': 'none',
            'vertical-align': 'middle',
            'css-class': '    mjml-tag  identifier-mj-section-58',
            'border-left': '10px solid #e6e6e6',
            'border-right': '10px solid #e6e6e6',
            'border-top': '0px none #e6e6e6',
            'border-bottom': '10px none #e6e6e6',
            'padding-right': '0',
            'padding-left': '0',
            'padding-top': '0',
            'padding-bottom': '0',
          },
          children: [
            {
              tagName: 'mj-column',
              attributes: {
                'css-class': '    mjml-tag  identifier-mj-column-57',
                padding: '0px 0px',
                'padding-left': '8px',
                'padding-right': '8px',
              },
              children: [
                {
                  tagName: 'mj-text',
                  attributes: {
                    color: '#000000',
                    'font-size': '13px',
                    'line-height': '1.3',
                    'letter-spacing': 'none',
                    align: 'left',
                    padding: '10px 25px',
                    'padding-left': '0px',
                    'padding-right': '0px',
                    'css-class': '    mjml-tag  identifier-mj-text-56',
                    'padding-bottom': '0px',
                  },
                  content:
                    'PGRpdj48YiBzdHlsZT0id29yZC1zcGFjaW5nOiBub3JtYWw7Ij48Zm9udCBzaXplPSIzIj5XYXJtIFJlZ2FyZHMsPC9mb250PjwvYj48YnI+PC9kaXY+PGRpdj48Zm9udCBzaXplPSIzIj5Hcm91cCBkZXNrPC9mb250PjwvZGl2Pg==',
                  mutableProperties: [
                    'color',
                    'font-family',
                    'font-size',
                    'font-style',
                    'font-weight',
                    'line-height',
                    'letter-spacing',
                    'height',
                    'text-decoration',
                    'text-transform',
                    'align',
                    'container-background-color',
                    'padding',
                    'padding-top',
                    'padding-bottom',
                    'padding-left',
                    'padding-right',
                    'css-class',
                  ],
                  mutalbePropertiesWithDefaultValues: {
                    color: '#000000',
                    'font-family': 'Ubuntu, Helvetica, Arial, sans-serif',
                    'font-size': '13px',
                    'font-style': '',
                    'font-weight': '',
                    'line-height': '1',
                    'letter-spacing': 'none',
                    height: '',
                    'text-decoration': '',
                    'text-transform': '',
                    align: 'left',
                    'container-background-color': '',
                    padding: '10px 25px',
                    'padding-top': '',
                    'padding-bottom': '',
                    'padding-left': '',
                    'padding-right': '',
                    'css-class': '',
                  },
                },
              ],
              mutableProperties: [
                'background-color',
                'inner-background-color',
                'border',
                'border-bottom',
                'border-left',
                'border-right',
                'border-top',
                'border-radius',
                'inner-border',
                'inner-border-bottom',
                'inner-border-left',
                'inner-border-right',
                'inner-border-top',
                'inner-border-radius',
                'width',
                'vertical-align',
                'padding',
                'padding-top',
                'padding-bottom',
                'padding-left',
                'padding-right',
                'css-class',
              ],
            },
          ],
          cannot_have: ['mj-section', 'mj-column'],
          mutableProperties: [
            'background-color',
            'background-position',
            'background-position-x',
            'background-position-y',
            'background-repeat',
            'background-size',
            'background-url',
            'border',
            'border-bottom',
            'border-left',
            'border-radius',
            'border-right',
            'border-top',
            'css-class',
            'direction',
            'full-width',
            'padding',
            'padding-bottom',
            'padding-left',
            'padding-right',
            'padding-top',
            'text-align',
          ],
        },
        {
          tagName: 'mj-section',
          attributes: {
            align: 'center',
            'background-color': '#ffffffff',
            border: 'none',
            'border-radius': '0px',
            color: '#ffffff',
            'font-family': 'Ubuntu, Helvetica, Arial, sans-serif',
            'font-size': '13px',
            'font-weight': 'normal',
            'inner-padding': '10px 25px',
            'line-height': '120%',
            padding: '10px 25px',
            target: '_blank',
            'text-align': 'center',
            'text-decoration': 'none',
            'text-transform': 'none',
            'vertical-align': 'middle',
            'css-class': '   mjml-tag  identifier-mj-section-39',
            'border-left': '10px solid #e6e6e6',
            'border-right': '10px solid #e6e6e6',
            'border-top': '0px none #e6e6e6',
            'border-bottom': '10px none #e6e6e6',
            'padding-right': '0',
            'padding-left': '0',
            'padding-top': '0',
            'padding-bottom': '0',
          },
          children: [
            {
              tagName: 'mj-column',
              attributes: {
                'css-class': '   mjml-tag  identifier-mj-column-38',
                padding: '0px 0px',
                'padding-left': '8px',
                'padding-right': '8px',
              },
              children: [
                {
                  tagName: 'mj-text',
                  attributes: {
                    color: '#000000',
                    'font-size': '13px',
                    'line-height': '1.3',
                    'letter-spacing': 'none',
                    align: 'left',
                    padding: '10px 25px',
                    'padding-left': '0px',
                    'padding-right': '0px',
                    'css-class': '   mjml-tag  identifier-mj-text-36',
                    'padding-bottom': '0px',
                  },
                  content:
                    'PGZvbnQgc2l6ZT0iMyI+PGk+UExFQVNFIERPIE5PVCBSRVBMWSBUTyBUSElTIEVNQUlMOyBUSElTIElTIEFOIEFVVE8gR0VORVJBVEVEIE1BSUwgQU5EIFJFUExJRVMgQVJFIE5PVCBNT05JVE9SRUQuIFBMRUFTRSBVU0UgT1VSIENPTlRBQ1QgUEFHRS48L2k+PC9mb250Pg==',
                  mutableProperties: [
                    'color',
                    'font-family',
                    'font-size',
                    'font-style',
                    'font-weight',
                    'line-height',
                    'letter-spacing',
                    'height',
                    'text-decoration',
                    'text-transform',
                    'align',
                    'container-background-color',
                    'padding',
                    'padding-top',
                    'padding-bottom',
                    'padding-left',
                    'padding-right',
                    'css-class',
                  ],
                  mutalbePropertiesWithDefaultValues: {
                    color: '#000000',
                    'font-family': 'Ubuntu, Helvetica, Arial, sans-serif',
                    'font-size': '13px',
                    'font-style': '',
                    'font-weight': '',
                    'line-height': '1',
                    'letter-spacing': 'none',
                    height: '',
                    'text-decoration': '',
                    'text-transform': '',
                    align: 'left',
                    'container-background-color': '',
                    padding: '10px 25px',
                    'padding-top': '',
                    'padding-bottom': '',
                    'padding-left': '',
                    'padding-right': '',
                    'css-class': '',
                  },
                },
                {
                  tagName: 'mj-spacer',
                  attributes: {
                    height: '20px',
                    padding: 'none',
                    'css-class': ' mjml-tag  identifier-mj-spacer-61',
                  },
                  children: [],
                  mutableProperties: [
                    'container-background-color',
                    'css-class',
                    'height',
                    'padding',
                    'padding-bottom',
                    'padding-left',
                    'padding-right',
                    'padding-top',
                  ],
                  mutalbePropertiesWithDefaultValues: {
                    'container-background-color': '',
                    'css-class': '',
                    height: '20px',
                    padding: 'none',
                    'padding-bottom': '',
                    'padding-left': '',
                    'padding-right': '',
                    'padding-top': '',
                  },
                },
                {
                  tagName: 'mj-divider',
                  attributes: {
                    'border-color': '#000000',
                    'border-style': 'solid',
                    'border-width': '4px',
                    padding: '0px',
                    width: '100%',
                    align: 'center',
                    'css-class': ' mjml-tag  identifier-mj-divider-62',
                  },
                  children: [],
                  mutableProperties: [
                    'border-color',
                    'border-style',
                    'border-width',
                    'container-background-color',
                    'css-class',
                    'padding',
                    'padding-bottom',
                    'padding-left',
                    'padding-right',
                    'padding-top',
                    'width',
                    'align',
                  ],
                  mutalbePropertiesWithDefaultValues: {
                    'border-color': '#000000',
                    'border-style': 'solid',
                    'border-width': '4px',
                    'container-background-color': '',
                    'css-class': '',
                    padding: '10px 25px',
                    'padding-bottom': '',
                    'padding-left': '',
                    'padding-right': '',
                    'padding-top': '',
                    width: '100%',
                    align: 'center',
                  },
                },
                {
                  tagName: 'mj-spacer',
                  attributes: {
                    height: '20px',
                    padding: 'none',
                    'css-class': ' mjml-tag  identifier-mj-spacer-63',
                  },
                  children: [],
                  mutableProperties: [
                    'container-background-color',
                    'css-class',
                    'height',
                    'padding',
                    'padding-bottom',
                    'padding-left',
                    'padding-right',
                    'padding-top',
                  ],
                  mutalbePropertiesWithDefaultValues: {
                    'container-background-color': '',
                    'css-class': '',
                    height: '20px',
                    padding: 'none',
                    'padding-bottom': '',
                    'padding-left': '',
                    'padding-right': '',
                    'padding-top': '',
                  },
                },
              ],
              mutableProperties: [
                'background-color',
                'inner-background-color',
                'border',
                'border-bottom',
                'border-left',
                'border-right',
                'border-top',
                'border-radius',
                'inner-border',
                'inner-border-bottom',
                'inner-border-left',
                'inner-border-right',
                'inner-border-top',
                'inner-border-radius',
                'width',
                'vertical-align',
                'padding',
                'padding-top',
                'padding-bottom',
                'padding-left',
                'padding-right',
                'css-class',
              ],
            },
          ],
          cannot_have: ['mj-section', 'mj-column'],
          mutableProperties: [
            'background-color',
            'background-position',
            'background-position-x',
            'background-position-y',
            'background-repeat',
            'background-size',
            'background-url',
            'border',
            'border-bottom',
            'border-left',
            'border-radius',
            'border-right',
            'border-top',
            'css-class',
            'direction',
            'full-width',
            'padding',
            'padding-bottom',
            'padding-left',
            'padding-right',
            'padding-top',
            'text-align',
          ],
        },
        {
          tagName: 'mj-section',
          attributes: {
            align: 'center',
            'background-color': '#ff0000ff',
            border: 'none',
            'border-radius': '0px',
            color: '#ffffff',
            'font-family': 'Ubuntu, Helvetica, Arial, sans-serif',
            'font-size': '13px',
            'font-weight': 'normal',
            'inner-padding': '10px 25px',
            'line-height': '120%',
            padding: '10px 25px',
            target: '_blank',
            'text-align': 'center',
            'text-decoration': 'none',
            'text-transform': 'none',
            'vertical-align': 'middle',
            'css-class': '  mjml-tag  identifier-mj-section-21',
            'border-left': '10px solid #e6e6e6',
            'border-right': '10px solid #e6e6e6',
            'border-top': '0px none #e6e6e6',
            'border-bottom': '10px solid #e6e6e6',
            'padding-right': '0',
            'padding-left': '0',
            'padding-top': '0',
            'padding-bottom': '0',
          },
          children: [
            {
              tagName: 'mj-column',
              attributes: {
                'css-class': '  mjml-tag  identifier-mj-column-20',
                padding: '0px 0px',
                width: '50%',
                'vertical-align': 'middle',
              },
              children: [
                {
                  tagName: 'mj-text',
                  attributes: {
                    color: '#000000',
                    'font-size': '13px',
                    'line-height': '1.5',
                    'letter-spacing': 'none',
                    align: 'center',
                    padding: '10px 25px',
                    'padding-left': '0px',
                    'padding-right': '0px',
                    'css-class': ' mjml-tag  identifier-mj-text-71',
                  },
                  content:
                    'PGZvbnQgY29sb3I9IiNmZmZmZmYiIHNpemU9IjQiIHN0eWxlPSIiPjxiPkdFVCBERUFMUywgT0ZGRVJTIEFORCBNT1JFIERFTElWRVJFRCBUTyBZT1VSIElOQk9YPC9iPjwvZm9udD4=',
                  mutableProperties: [
                    'color',
                    'font-family',
                    'font-size',
                    'font-style',
                    'font-weight',
                    'line-height',
                    'letter-spacing',
                    'height',
                    'text-decoration',
                    'text-transform',
                    'align',
                    'container-background-color',
                    'padding',
                    'padding-top',
                    'padding-bottom',
                    'padding-left',
                    'padding-right',
                    'css-class',
                  ],
                  mutalbePropertiesWithDefaultValues: {
                    color: '#000000',
                    'font-family': 'Ubuntu, Helvetica, Arial, sans-serif',
                    'font-size': '13px',
                    'font-style': '',
                    'font-weight': '',
                    'line-height': '1',
                    'letter-spacing': 'none',
                    height: '',
                    'text-decoration': '',
                    'text-transform': '',
                    align: 'left',
                    'container-background-color': '',
                    padding: '10px 25px',
                    'padding-top': '',
                    'padding-bottom': '',
                    'padding-left': '',
                    'padding-right': '',
                    'css-class': '',
                  },
                },
              ],
              mutableProperties: [
                'background-color',
                'inner-background-color',
                'border',
                'border-bottom',
                'border-left',
                'border-right',
                'border-top',
                'border-radius',
                'inner-border',
                'inner-border-bottom',
                'inner-border-left',
                'inner-border-right',
                'inner-border-top',
                'inner-border-radius',
                'width',
                'vertical-align',
                'padding',
                'padding-top',
                'padding-bottom',
                'padding-left',
                'padding-right',
                'css-class',
              ],
            },
            {
              tagName: 'mj-column',
              attributes: {
                'css-class': ' mjml-tag  identifier-mj-column-70',
                padding: '0px 0px',
                width: '50%',
                'vertical-align': 'middle',
                'border-top': '0px none #000',
                'border-right': '0px none #000',
                'border-left': '0px none #000',
                'border-bottom': '0px none #000',
              },
              children: [
                {
                  tagName: 'mj-button',
                  attributes: {
                    align: 'center',
                    'background-color': '#ff0000ff',
                    border: 'none',
                    'border-radius': '3px',
                    color: '#ffffff',
                    'font-family': 'Ubuntu, Helvetica, Arial, sans-serif',
                    'font-size': '13px',
                    'font-weight': 'normal',
                    'inner-padding': '10px 48px',
                    'line-height': '120%',
                    padding: '10px 25px',
                    target: '_blank',
                    'text-align': 'none',
                    'text-decoration': 'none',
                    'text-transform': 'none',
                    'vertical-align': 'middle',
                    'css-class': ' mjml-tag  identifier-mj-button-72',
                    'border-left': '1px solid #ffffff',
                    'border-right': '1px solid #ffffff',
                    'border-top': '1px solid #ffffff',
                    'border-bottom': '1px solid #ffffff',
                    'padding-top': '8px',
                    'padding-right': '0',
                    'padding-bottom': '8px',
                    'padding-left': '0',
                  },
                  children: [],
                  content: 'U0lHTiBVUCBOT1c=',
                  mutableProperties: [
                    'align',
                    'background-color',
                    'border',
                    'border-bottom',
                    'border-left',
                    'border-radius',
                    'border-right',
                    'border-top',
                    'color',
                    'container-background-color',
                    'css-class',
                    'font-family',
                    'font-size',
                    'font-style',
                    'font-weight',
                    'height',
                    'href',
                    'inner-padding',
                    'letter-spacing',
                    'line-height',
                    'padding',
                    'padding-bottom',
                    'padding-left',
                    'padding-right',
                    'padding-top',
                    'rel',
                    'target',
                    'text-align',
                    'text-decoration',
                    'text-transform',
                    'title',
                    'vertical-align',
                    'width',
                  ],
                  mutalbePropertiesWithDefaultValues: {
                    align: 'center',
                    'background-color': '#414141',
                    border: 'none',
                    'border-bottom': '',
                    'border-left': '',
                    'border-radius': '3px',
                    'border-right': '',
                    'border-top': '',
                    color: '#ffffff',
                    'container-background-color': '',
                    'css-class': '',
                    'font-family': 'Ubuntu, Helvetica, Arial, sans-serif',
                    'font-size': '13px',
                    'font-style': '',
                    'font-weight': 'normal',
                    height: '',
                    href: '',
                    'inner-padding': '10px 25px',
                    'letter-spacing': '',
                    'line-height': '120%',
                    padding: '10px 25px',
                    'padding-bottom': '',
                    'padding-left': '',
                    'padding-right': '',
                    'padding-top': '',
                    rel: '',
                    target: '_blank',
                    'text-align': 'none',
                    'text-decoration': 'none',
                    'text-transform': 'none',
                    title: '',
                    'vertical-align': 'middle',
                    width: '',
                  },
                },
              ],
              mutableProperties: [
                'background-color',
                'inner-background-color',
                'border',
                'border-bottom',
                'border-left',
                'border-right',
                'border-top',
                'border-radius',
                'inner-border',
                'inner-border-bottom',
                'inner-border-left',
                'inner-border-right',
                'inner-border-top',
                'inner-border-radius',
                'width',
                'vertical-align',
                'padding',
                'padding-top',
                'padding-bottom',
                'padding-left',
                'padding-right',
                'css-class',
              ],
            },
          ],
          cannot_have: ['mj-section', 'mj-column'],
          mutableProperties: [
            'background-color',
            'background-position',
            'background-position-x',
            'background-position-y',
            'background-repeat',
            'background-size',
            'background-url',
            'border',
            'border-bottom',
            'border-left',
            'border-radius',
            'border-right',
            'border-top',
            'css-class',
            'direction',
            'full-width',
            'padding',
            'padding-bottom',
            'padding-left',
            'padding-right',
            'padding-top',
            'text-align',
          ],
        },
      ],
      mutableProperties: ['width', 'background-color'],
    },
  ],
  attributes: {},
};
